version: 0.0
os: linux
files:
  - source: / # Deploy everything in the root of the repository
    destination: /home/ubuntu/aura-frontend # Adjust the destination as needed
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
